// Cross-language contract: the shared JSON vectors are generated by the
// authoritative C# engine. The TypeScript engine MUST reproduce every
// expectedFinalScore and expectedWin, replaying through the same common
// interface the API uses (solitaireEngines.for(variant).replay(...)).

import { describe, expect, it } from 'vitest';
import klondikeJson from '../../../../shared/vectors/klondike.json';
import spiderJson from '../../../../shared/vectors/spider.json';
import freecellJson from '../../../../shared/vectors/freecell.json';
import pyramidJson from '../../../../shared/vectors/pyramid.json';
import { solitaireEngines } from '../engines';
import type { GameDefinition } from '../types';

interface Vector {
  readonly name: string;
  readonly variant: string;
  readonly seed: number;
  readonly options: Record<string, number>;
  readonly moves: GameDefinition['moves'];
  readonly expectedFinalScore: number;
  readonly expectedWin: boolean;
}

interface VectorFile {
  readonly description: string;
  readonly vectors: readonly Vector[];
}

const files: readonly VectorFile[] = [klondikeJson, spiderJson, freecellJson, pyramidJson];

for (const file of files) {
  const title = file.description.split('.')[0] ?? 'vectors';
  describe(title, () => {
    const vectors = file.vectors;

    it('contains at least one vector', () => {
      expect(vectors.length).toBeGreaterThan(0);
    });

    for (const vector of vectors) {
      it(`${vector.name}: score ${vector.expectedFinalScore}, win=${vector.expectedWin}`, () => {
        const engine = solitaireEngines.for(vector.variant);
        const outcome = engine.replay({
          seed: vector.seed,
          options: vector.options,
          moves: vector.moves,
        });

        // Every committed vector is a valid sequence.
        expect(outcome.allMovesLegal).toBe(true);
        expect(outcome.score).toBe(vector.expectedFinalScore);
        expect(outcome.won).toBe(vector.expectedWin);
      });
    }
  });
}
