using System.Text.Json;
using System.Text.Json.Serialization;

namespace Solitaire.Engine.Tests;

// DTOs mirror the JSON shape of /shared/vectors/*.json. Options is a portable
// string→int bag (exactly GameDefinition.Options), so every variant shares one
// file format and the API can verify any of them through ISolitaireEngine.
internal sealed record VectorDto(
    string Name,
    string Variant,
    int Seed,
    IReadOnlyDictionary<string, int> Options,
    IReadOnlyList<MoveDto> Moves,
    int ExpectedFinalScore,
    bool ExpectedWin);

internal sealed record VectorFileDto(string Description, IReadOnlyList<VectorDto> Vectors);

// A vector definition before expected values are computed.
internal sealed record VectorCase(
    string Name,
    string Variant,
    int Seed,
    IReadOnlyDictionary<string, int> Options,
    IReadOnlyList<MoveDto> Moves);

/// <summary>
/// Builds the cross-language test vectors for each variant and handles their JSON
/// (de)serialization and file location. Expected scores/outcomes are computed
/// through the uniform <see cref="ISolitaireEngine"/> so the files stay in lockstep
/// with the authoritative engine and also exercise the common interface.
/// </summary>
internal static class VectorData
{
    public static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    public static IReadOnlyList<string> FileNames { get; } =
        ["klondike.json", "spider.json", "freecell.json", "pyramid.json", "tripeaks.json"];

    /// <summary>All canonical vector definitions for a given file/variant family.</summary>
    public static IReadOnlyList<VectorCase> BuildCases(string fileName) => fileName switch
    {
        "klondike.json" => BuildKlondikeCases(),
        "spider.json" => BuildSpiderCases(),
        "freecell.json" => BuildFreeCellCases(),
        "pyramid.json" => BuildPyramidCases(),
        "tripeaks.json" => BuildTriPeaksCases(),
        _ => throw new ArgumentOutOfRangeException(nameof(fileName), fileName, "Unknown vector file."),
    };

    public static string DescriptionFor(string fileName) =>
        $"Cross-language {Path.GetFileNameWithoutExtension(fileName)} test vectors. Each vector is a valid "
        + "move sequence; replaying {seed, options, moves} through the engine must yield expectedFinalScore "
        + "and expectedWin. Options is a string->int bag. Generated by Solitaire.Engine.Tests; do not edit by hand.";

    /// <summary>Builds the full file DTO with expected outcomes from the uniform engine.</summary>
    public static VectorFileDto BuildFile(string fileName)
    {
        var vectors = new List<VectorDto>();
        foreach (var c in BuildCases(fileName))
        {
            var engine = SolitaireEngines.For(c.Variant);
            var outcome = engine.Replay(new GameDefinition(c.Seed, c.Options, c.Moves));
            vectors.Add(new VectorDto(
                c.Name, c.Variant, c.Seed, c.Options, c.Moves, outcome.Score, outcome.Won));
        }

        return new VectorFileDto(DescriptionFor(fileName), vectors);
    }

    public static string Serialize(VectorFileDto file) => JsonSerializer.Serialize(file, JsonOptions);

    public static VectorFileDto Deserialize(string json) =>
        JsonSerializer.Deserialize<VectorFileDto>(json, JsonOptions)
        ?? throw new InvalidOperationException("Vector file deserialized to null.");

    /// <summary>Absolute path to /shared/vectors/{fileName}, located relative to the repo root.</summary>
    public static string VectorFilePath(string fileName)
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            bool isRepoRoot = Directory.Exists(Path.Combine(dir.FullName, ".git"))
                || (Directory.Exists(Path.Combine(dir.FullName, "shared"))
                    && Directory.Exists(Path.Combine(dir.FullName, "backend")));
            if (isRepoRoot)
            {
                return Path.Combine(dir.FullName, "shared", "vectors", fileName);
            }

            dir = dir.Parent;
        }

        throw new InvalidOperationException("Could not locate repository root from " + AppContext.BaseDirectory);
    }

    // ---- Klondike ---------------------------------------------------------

    private static IReadOnlyList<VectorCase> BuildKlondikeCases()
    {
        var win2 = KlondikeSolver.Solve(2, GameOptions.DrawOne)
            ?? throw new InvalidOperationException("seed 2 (draw-1) expected to be solvable.");
        var win4 = KlondikeSolver.Solve(4, GameOptions.DrawOne)
            ?? throw new InvalidOperationException("seed 4 (draw-1) expected to be solvable.");

        // Deal-independent draw-3 sequence: empty the 24-card stock (8 draws) then recycle.
        var drawThreeRecycle = new List<Move>();
        for (int i = 0; i < 8; i++)
        {
            drawThreeRecycle.Add(Move.Draw());
        }

        drawThreeRecycle.Add(Move.Recycle());

        return
        [
            Klondike("draw1-seed2-win", 2, GameOptions.DrawOne, win2),
            Klondike("draw1-seed4-win", 4, GameOptions.DrawOne, win4),
            Klondike("draw1-seed2-partial", 2, GameOptions.DrawOne, win2.Take(40).ToList()),
            Klondike("draw3-seed7-recycle", 7, GameOptions.DrawThree, drawThreeRecycle),
        ];
    }

    private static VectorCase Klondike(string name, int seed, GameOptions options, IReadOnlyList<Move> moves) =>
        new(
            name,
            "klondike",
            seed,
            new Dictionary<string, int> { ["drawCount"] = options.DrawCount, ["maxRedeals"] = options.MaxRedeals },
            moves.Select(global::Solitaire.Engine.Klondike.ToDto).ToList());

    // ---- Spider -----------------------------------------------------------

    private static IReadOnlyList<VectorCase> BuildSpiderCases()
    {
        // Deal-independent 1-suit sequence: five deals empty the stock.
        var fiveDeals = Enumerable.Range(0, 5).Select(_ => SpiderMove.Deal()).ToList();

        return
        [
            Spider("spider1-seed2-play", 2, SpiderOptions.OneSuit,
                SpiderSolver.GreedyPlaythrough(2, SpiderOptions.OneSuit, 300)),
            Spider("spider2-seed1-play", 1, SpiderOptions.TwoSuit,
                SpiderSolver.GreedyPlaythrough(1, SpiderOptions.TwoSuit, 120)),
            Spider("spider4-seed5-play", 5, SpiderOptions.FourSuit,
                SpiderSolver.GreedyPlaythrough(5, SpiderOptions.FourSuit, 120)),
            Spider("spider1-seed3-deal5", 3, SpiderOptions.OneSuit, fiveDeals),
        ];
    }

    private static VectorCase Spider(string name, int seed, SpiderOptions options, IReadOnlyList<SpiderMove> moves) =>
        new(
            name,
            "spider",
            seed,
            new Dictionary<string, int> { ["suitCount"] = options.SuitCount },
            moves.Select(global::Solitaire.Engine.Spider.ToDto).ToList());

    // ---- FreeCell -----------------------------------------------------------

    private static IReadOnlyList<VectorCase> BuildFreeCellCases()
    {
        // Like Spider, FreeCell's branching factor (8 columns, free cells,
        // supermoves, any-card-on-empty) makes it not reliably solvable by a
        // simple search within a small budget, so these are realistic greedy
        // playthroughs rather than guaranteed wins — see FreeCellSolver's remarks.
        return
        [
            FreeCellCase("freecell-seed1-play", 1, FreeCellSolver.GreedyPlaythrough(1, 300)),
            FreeCellCase("freecell-seed2-play", 2, FreeCellSolver.GreedyPlaythrough(2, 300)),
            FreeCellCase("freecell-seed3-short", 3, FreeCellSolver.GreedyPlaythrough(3, 10)),
        ];
    }

    private static VectorCase FreeCellCase(string name, int seed, IReadOnlyList<FreeCellMove> moves) =>
        new(
            name,
            "freecell",
            seed,
            new Dictionary<string, int>(),
            moves.Select(global::Solitaire.Engine.FreeCell.ToDto).ToList());

    // ---- Pyramid --------------------------------------------------------------

    private static IReadOnlyList<VectorCase> BuildPyramidCases()
    {
        // Same reasoning as FreeCell/Spider: a greedy (non-backtracking) line is
        // enough for cross-language parity; win detection itself is covered by
        // cheap direct unit tests (PyramidMoveLegalityTests.IsWon_*).
        return
        [
            PyramidCase("pyramid-seed1-play", 1, PyramidSolver.GreedyPlaythrough(1, 200)),
            PyramidCase("pyramid-seed2-play", 2, PyramidSolver.GreedyPlaythrough(2, 200)),
            PyramidCase("pyramid-seed3-short", 3, PyramidSolver.GreedyPlaythrough(3, 8)),
        ];
    }

    private static VectorCase PyramidCase(string name, int seed, IReadOnlyList<PyramidMove> moves) =>
        new(
            name,
            "pyramid",
            seed,
            new Dictionary<string, int>(),
            moves.Select(global::Solitaire.Engine.Pyramid.ToDto).ToList());

    // ---- TriPeaks --------------------------------------------------------------

    private static IReadOnlyList<VectorCase> BuildTriPeaksCases()
    {
        // Same reasoning as Pyramid/FreeCell/Spider: a greedy (non-backtracking)
        // line is enough for cross-language parity; win detection itself is
        // covered by cheap direct unit tests (TriPeaksMoveLegalityTests.IsWon_*).
        return
        [
            TriPeaksCase("tripeaks-seed1-play", 1, TriPeaksSolver.GreedyPlaythrough(1, 200)),
            TriPeaksCase("tripeaks-seed2-play", 2, TriPeaksSolver.GreedyPlaythrough(2, 200)),
            TriPeaksCase("tripeaks-seed3-short", 3, TriPeaksSolver.GreedyPlaythrough(3, 8)),
        ];
    }

    private static VectorCase TriPeaksCase(string name, int seed, IReadOnlyList<TriPeaksMove> moves) =>
        new(
            name,
            "tripeaks",
            seed,
            new Dictionary<string, int>(),
            moves.Select(global::Solitaire.Engine.TriPeaks.ToDto).ToList());
}
