using System.Text.Json;
using System.Text.Json.Serialization;

namespace Solitaire.Engine.Tests;

// DTOs mirror the JSON shape of /shared/vectors/klondike.json. Kept intentionally
// small and explicit so the future TypeScript engine can parse the same file.
internal sealed record OptionsDto(int DrawCount, int MaxRedeals);

internal sealed record MoveDto(string Type, int? Source, int? Destination, int? Count);

internal sealed record VectorDto(
    string Name,
    int Seed,
    OptionsDto Options,
    IReadOnlyList<MoveDto> Moves,
    int ExpectedFinalScore,
    bool ExpectedWin);

internal sealed record VectorFileDto(string Description, IReadOnlyList<VectorDto> Vectors);

/// <summary>
/// Builds the canonical set of cross-language test vectors and handles their
/// JSON (de)serialization and file location. Expected scores/outcomes are always
/// computed by the authoritative C# engine so the file stays in lockstep with it.
/// </summary>
internal static class VectorData
{
    public const string FileDescription =
        "Cross-language Klondike test vectors. Each vector is a valid move sequence; "
        + "replaying {seed, options, moves} through the engine must yield expectedFinalScore "
        + "and expectedWin. maxRedeals == 2147483647 means unlimited. Generated by "
        + "Solitaire.Engine.Tests; do not edit by hand.";

    public static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    /// <summary>The canonical vector definitions (before expected values are computed).</summary>
    public static IReadOnlyList<(string Name, int Seed, GameOptions Options, IReadOnlyList<Move> Moves)>
        BuildCases()
    {
        var solvedSeed2 = KlondikeSolver.Solve(2, GameOptions.DrawOne)
            ?? throw new InvalidOperationException("seed 2 (draw-1) expected to be solvable.");
        var solvedSeed4 = KlondikeSolver.Solve(4, GameOptions.DrawOne)
            ?? throw new InvalidOperationException("seed 4 (draw-1) expected to be solvable.");

        // A deal-independent draw-3 sequence: empty the 24-card stock (8 draws),
        // then a single recycle. Exercises draw-3 and the recycle penalty/clamp.
        var drawThreeRecycle = new List<Move>();
        for (int i = 0; i < 8; i++)
        {
            drawThreeRecycle.Add(Move.Draw());
        }

        drawThreeRecycle.Add(Move.Recycle());

        return
        [
            ("draw1-seed2-win", 2, GameOptions.DrawOne, solvedSeed2),
            ("draw1-seed4-win", 4, GameOptions.DrawOne, solvedSeed4),
            ("draw1-seed2-partial", 2, GameOptions.DrawOne, solvedSeed2.Take(40).ToList()),
            ("draw3-seed7-recycle", 7, GameOptions.DrawThree, drawThreeRecycle),
        ];
    }

    /// <summary>Builds the full file DTO with expected scores/outcomes from the engine.</summary>
    public static VectorFileDto BuildFileDto()
    {
        var vectors = new List<VectorDto>();
        foreach (var (name, seed, options, moves) in BuildCases())
        {
            var result = Klondike.Replay(seed, options, moves);
            vectors.Add(new VectorDto(
                Name: name,
                Seed: seed,
                Options: new OptionsDto(options.DrawCount, options.MaxRedeals),
                Moves: moves.Select(ToDto).ToList(),
                ExpectedFinalScore: result.Score,
                ExpectedWin: result.Won));
        }

        return new VectorFileDto(FileDescription, vectors);
    }

    public static string Serialize(VectorFileDto file) => JsonSerializer.Serialize(file, JsonOptions);

    public static VectorFileDto Deserialize(string json) =>
        JsonSerializer.Deserialize<VectorFileDto>(json, JsonOptions)
        ?? throw new InvalidOperationException("Vector file deserialized to null.");

    public static MoveDto ToDto(Move move) => move.Type switch
    {
        MoveType.Draw => new MoveDto("Draw", null, null, null),
        MoveType.Recycle => new MoveDto("Recycle", null, null, null),
        MoveType.WasteToFoundation => new MoveDto("WasteToFoundation", null, null, null),
        MoveType.WasteToTableau => new MoveDto("WasteToTableau", null, move.Destination, null),
        MoveType.TableauToFoundation => new MoveDto("TableauToFoundation", move.Source, null, null),
        MoveType.FoundationToTableau =>
            new MoveDto("FoundationToTableau", move.Source, move.Destination, null),
        MoveType.TableauToTableau =>
            new MoveDto("TableauToTableau", move.Source, move.Destination, move.Count),
        _ => throw new ArgumentOutOfRangeException(nameof(move)),
    };

    public static Move FromDto(MoveDto dto) => dto.Type switch
    {
        "Draw" => Move.Draw(),
        "Recycle" => Move.Recycle(),
        "WasteToFoundation" => Move.WasteToFoundation(),
        "WasteToTableau" => Move.WasteToTableau(Require(dto.Destination)),
        "TableauToFoundation" => Move.TableauToFoundation(Require(dto.Source)),
        "FoundationToTableau" =>
            Move.FoundationToTableau((Suit)Require(dto.Source), Require(dto.Destination)),
        "TableauToTableau" =>
            Move.TableauToTableau(Require(dto.Source), Require(dto.Destination), Require(dto.Count)),
        _ => throw new ArgumentOutOfRangeException(nameof(dto), dto.Type, "Unknown move type."),
    };

    private static int Require(int? value) =>
        value ?? throw new InvalidOperationException("Move field missing in vector.");

    /// <summary>Absolute path to /shared/vectors/klondike.json, located relative to the repo root.</summary>
    public static string VectorFilePath()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            bool isRepoRoot = Directory.Exists(Path.Combine(dir.FullName, ".git"))
                || (Directory.Exists(Path.Combine(dir.FullName, "shared"))
                    && Directory.Exists(Path.Combine(dir.FullName, "backend")));
            if (isRepoRoot)
            {
                return Path.Combine(dir.FullName, "shared", "vectors", "klondike.json");
            }

            dir = dir.Parent;
        }

        throw new InvalidOperationException("Could not locate repository root from " + AppContext.BaseDirectory);
    }
}
